### ISSUE TITLE
Replicate classical examples

### ISSUE THREAD

**Issue by dani-guijo** [dani-guijo/quantum-power-system-state-estimation#2]
Using the classical methods from the literature, get preliminary results for the examples 2.2 to 2.6 in the book.

**Comment by LeanderReascos** [comment]
## Weighted Least Squares State Estimation: Classical Method

This commit introduces the addition of Python code implementing the classical method for power state estimation. The method utilizes the Weighted Least Squares State Estimation approach as described in the book *Power System State Estimation: Theory and Implementation* by Ali Abur and Antonio Gomez Exposito. The code has been validated through testing on the example provided in Section 2 of the mentioned book, up to Example 2.6.

The Python code includes a class named `WeightedLeastSquaresSE`, designed to handle input data in the following format:

- `Z`: Array of measurements (type, nodes, value, sigma)
- `R`: Resistance Matrix
- `X`: Reactance Matrix
- `Edges`: List of edges (i, j) where i and j are the nodes

The supported measurement types are as follows:

| Type | Description | 
|------|-------------|
| 0    | Voltage     |
| 1    | Power Flow between two nodes (Real) |
| 2    | Power Flow between two nodes (Imaginary) |
| 3    | Power injection at a node (Real) |
| 4    | Power injection at a node (Imaginary) |

The `WeightedLeastSquaresSE` class provides functionality to calculate the Measurements Jacobian Matrix $H$ (`get_H(x)`) given an input state $\vec x$, the Gain Matrix $G$ (`get_G(H)`) given $H$ and the estimations $h(x)$ (`get_h()`).

Additionally, the class facilitates the estimation of the system state using the `solve()` method. This commit aims to enhance the repository with an efficient and validated implementation of the classical power state estimation method.
