### ISSUE TITLE
Add VQLS

### ISSUE THREAD

**Issue by dani-guijo** [dani-guijo/quantum-power-system-state-estimation#8]

**Comment by LeanderReascos** [comment]
# Variational Quantum Linear Solver (VQLS)
The VQLS.py file introduces the Variational Quantum Linear Solver (VQLS) class, which facilitates solving linear systems of equations using variational quantum algorithms. Leveraging PennyLane for quantum computation and NumPy for numerical operations, this class offers a comprehensive solution for quantum linear system solving. It allows setting up the problem with a given matrix A and vector b, and optimizing the variational parameters to find the solution.

# Changes in solvers.py:  Quantum Weighted Least Squares (QWLS) 

The solvers.py file introduces the Quantum Weighted Least Squares (QWLS) solver, which builds upon the functionality provided by the VQLS class. QWLS utilizes variational quantum algorithms to solve weighted least squares problems
